name: Production deploy
on:
   push:
    branches:
      - main
jobs:
  build:
    name: "Build production image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          target: prod
          tags: ${{ github.repository }}:prod
permissions:
  contents: read
  packages: write